# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Category.destroy_all
Product.destroy_all


Category.create(name: "oil cleanser")
Category.create(name: "water based cleanser")
Category.create(name: "exfoliator")
Category.create(name: "toner")
Category.create(name: "serum")
Category.create(name: "mask")
Category.create(name: "eyecream")
Category.create(name: "moisturizer")
Category.create(name: "sunscreen")
Category.create(name: "facial oil")

# Oil Cleanser

Product.create(name: "SQUALANE + ANTIOXIDANT CLEANSING OIL", brand: "Biossance", description: "The lightweight oil lifts away makeup and impurities, then rinses completely clean with water. Formulated with our sugarcane-derived, sustainable squalane oil, it helps keep skin hydrated and feeling fresh.", skintype: "all", category_id: 1, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/Cleansing-Oil_Full_white-1160-x-1160_580x@2x.png?v=1560972953")
Product.create(name: "Pre Cleanse Oil", brand: "True Botanicals", description: "This silky oil thoroughly loosens dirt, sunscreen, and stubborn makeup. Remove with cleanser or warm wash cloth to purify pores. Leaves skin clean, hydrated, and dewy.", skintype: "all", category_id: 1, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/pre-cleanse-oil_012de282-978a-4ec9-a9b0-67610ba1d613_x570.png?v=1557756849")
Product.create(name: "Nourishing Oil Cleanser", brand: "Tata Harper", description: "A multi-vitamin cleansing oil that breaks down buildup and dissolves makeup without stripping the skin for a soft, supple feeling. Best for makeup removal and dry, uneven skin.", skintype: "dry", category_id: 1, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/n/o/nourishing-oil-cleanser_goop.jpg")
Product.create(name: "Modern Friction", brand: "Origins", description: "Cleansing Oil With Radiance-Boosting White & Purple Rice. Add some luxury to your lather. This gentle, dual phase cleanser transforms with water from silky oil to creamy milk. Infused with radiance-boosting White and Purple Rice, it illuminates skin as it melts away dirt, makeup and impurities. Skin feels comfortably clean and soft, looks positively luminous. ", skintype: "all", category_id: 1, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0NWM01_1000x1000_0.jpg")
Product.create(name: "Clean Energy", brand: "Origins", description: "This lightweight formula with non-comedogenic Olive, Sunflower, Sesame and Safflower Oils removes dirt, makeup and pollutants with high efficiency. Kukui Nut and Macadamia help protect natural moisture. Skin breathes freely. And the energizing aroma of Grapefruit, Orange and Lemon renews your spirits.", skintype: "all", category_id: 1, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_ORG479_1000x1000_0.jpg")
Product.create(name: "Slaai Makeup-Melting Butter Cleanser", brand: "Drunk Elephant", description: "An innovative cleansing balm that melts all traces of dirt, makeup and sunscreen from skin.  Gentle enough to be used around the eye area, it quickly transforms from oil to milk upon contact with water. Effortlessly removes even water-resistant formulations and is free of PEGs and essential oils. Formulated with clean, antioxidant-rich fruit extracts and oils to help soothe, plus a nourishing African oil blend of marula, baobob, kalahari melon, mongongo and ximenia, Slaai™ Makeup-Melting Butter Cleanser cleanses and moisturizes without any irritants or sensitizers. Designed to be used on dry skin, Slaai removes excess oil, grime and makeup from skin. Adding water activates Slaai™ into a milk that rinses away cleanly, leaving behind a dewy glow.", skintype: "all", category_id: 1, img_path: "https://www.sephora.com/productimages/product/p442566-av-04-zoom.jpg")


# Water based cleanser
Product.create(name: "Bamboo Charcoal Cleanser", brand: "Herbivore", description: "Bamboo Charcoal has been used for centuries in the Far East. Bamboo charcoal does wonders to purify the skin by cleansing it of dirt, drawing impurities from deep within your pores. Gentle yet effective, Bamboo Charcoal works especially well to clean and care for oily, combination and blemish-prone skin types.", skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1320-25C_HBV_HIR_BAMBOOCHARCOAL_SOAP.jpg?v=1562001461")
Product.create(name: "Renew Nourishing Cleanser", brand: "True Botanicals", description: "A gentle cleanser for aging and dry skin that nourishes as it cleanses.", skintype: "dry", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-nourishing-cleanser-award_x570.png?v=1560277394")
Product.create(name: "Clear Nourishing Cleanser", brand: "True Botanicals", description: "A purifying cleanser for oily and breakout-prone skin that nourishes as it cleanses and gently exfoliates." ,skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-nourishing-cleanser_x570.png?v=1557756826")
Product.create(name: "Milky Jelly Cleanser", brand: "Glossier", description: "This is the ultimate daily face wash: use on dry skin to dissolve away makeup and grime, or on wet skin as you start your day. The pH-balanced, creamy gel formula is made with a blend of five skin conditioners so your face is left feeling healthy and soft, never tight. Its cleansing power comes from the same gentle cleaning agents found in contact lens solution, so it’s tough on impurities and still safe to use on your eyes. You’ll see." ,skintype: "all", category_id: 2, img_path: "https://static-assets.glossier.com/production/spree/images/attachments/000/003/760/portrait_normal/MilkyJellyCleanser.jpg?1556563755")
Product.create(name: "Checks And Balances", brand: "Origins", description: "Our clever cleanser balances faces with dry and oily places. This gentle, frothy face wash with Broad Leaf Kelp Extract, Wheat Protein and Tourmaline discourages excess oil production while protecting dry prone zones. Plus the aroma of Bergamot, Spearmint and Lavender refreshes. Skin feels comfortably clean. Never tight, pulled or parched.", skintype: "combination", category_id: 2, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_048E01_1000x1000_0.jpg")
Product.create(name: "Face Cleanser", brand: "First Aid Beauty", description: "A fragrance-free, gentle cleanser that effectively removes makeup, dirt and grime, leaving skin soft and supple. The whipped texture transforms into a sumptuous cream when blended with water.", skintype: "all", category_id: 2, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/0/200_face-cleaner_01-hero.jpg")
Product.create(name: "Beste No. 9 Jelly Cleanser", brand: "Drunk Elephant", description: "An innovative jelly cleanser that removes all traces of makeup, excess oil, pollution, and any other grime from the day. Free of SLS, fragrance, and essential oils, Beste™ No. 9 is totally non-irritating, non-sensitizing, and appropriate for all skin. Beste No. 9 is formulated at an ideal, non-stripping pH level of 5.5. With a unique blend of mild surfactants and makeup-dissolving emollients, this gentle formula rinses away without an ounce of residue, leaving skin clean and soft.", skintype: "all", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/Beste_Selling_Shot-Aug18_1024px72dpi_1024x1024.jpg?v=1558126154")
Product.create(name: "Peke Cleansing Bar", brand: "Drunk Elephant", description: "A gentle, multitasking bar that cleanses, tones, and moisturizes leaving the complexion perfectly balanced, soft, and supple. In a league of its own, The Pekee Bar clarifies, balances, and moisturizes while rinsing away pore-clogging surface debris, impurities, and excess oil. Infused with a blend of blueberry extract, marula oil, and honey, the Pekee Bar™ tones and promotes moisture retention while improving the feel of elasticity and firmness. The Pekee Bar™ is totally fragrance- and soap-free and formulated with only skin-friendly ingredients designed to cleanse and calm the skin. ", skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/pekee-web_1024x1024.jpg?v=1532024313")
Product.create(name: "Juju Bar", brand: "Drunk Elephant", description: "An ultra-mild, 3-in-1 bar that deeply cleanses and subtly exfoliates for a complexion that is soft and smooth. This multi-tasking bar is designed to effectively cleanse while gently removing dead skin cells from the surface of the skin. Our unique formulation of thermal mud and bamboo powder creates a wonderful creamy lather that dissolves unwanted oil, rinsing away pore-clogging surface debris and any impurities. It refines skin texture, brightens skin clarity, and over time, helps minimizes the look of pores.", skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/juju-web_1024x1024.jpg?v=1534290891")


# Exfoliator
Product.create(name: "Resurface Scrub", brand: "NOTO", description: "Welcome to your new favorite scrub of all time...Skin so smooth - you’ll be amazed .  Polish and cleanse  with Blood orange, alpha hydroxy acids and walnut powder, combining to create a gentle exfoliate that leaves your skin feeling brand new.  We recommend using this scrub twice a week - and please do protect your skin after use as AHA’s can leave skin sensitive towards the sun.", skintype: "all", category_id: 3, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-054-High-Res_1500x1500.jpg?v=1549926757")
Product.create(name: "Vitamin C Probiotic Face Polish", brand: "OSEA", description: "This potent powdered exfoliant instantly brightens as it polishes to reveal luminous, vibrant skin. Our unique formulation is the first to combine pure Vitamin C with vegan Probiotics. Reduces the look of hyperpigmentation, smoothes & visibly brightens your complexion. Fermented Pomegranate enzymes gently remove surface build-up. Finely ground organic Bamboo and Rice powders infused with mineral-rich Seaweeds work to delicately buff away dull skin. Our ultra-potent, preservative-free formula is kept fresh until activated with water, transforming it into a creamy paste for a youthful, luminous glow.", skintype: "all", category_id: 3, img_path: "https://cdn.shopify.com/s/files/1/1368/9993/products/OSEA-vitamin-c-probiotic-polish-r_db1b24a7-9ab9-4f70-bf2f-9c2372d01735.jpg?v=1544734230")
Product.create(name: "Solution", brand: "Glossier", description: "Unlike physical exfoliators that scrub the surface of your skin, Solution gently sloughs away dead skin through chemical exfoliation, revealing a fresh complexion. Daily use helps clear up acne and blackheads and reduces visible redness and enlarged pores. Overall, skin’s texture appears smoother, softer, and glowier. Solution contains a particular 10% blend of three acid groups: Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), and Polyhydroxy Acid (PHA). Acids are your friend.", skintype: "all", category_id: 3, img_path: "https://static-assets.glossier.com/production/spree/images/attachments/000/003/765/portrait_normal/Solution.jpg?1556564148")
Product.create(name: "Original Skin", brand: "Origins", description: "Glow big with our innovative 2-in-1mask! Made with Mediterranean Rose Clay, Canadian Willow Herb and exfoliating Jojoba beads, it helps gently deep clean while refining skin's texture. Pores appear to vanish. Clarity is restored. Glow is instant.", skintype: "combination", category_id: 3, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0T7H01_1000x1000_0.jpg")
Product.create(name: "Facial Radiance Pads", brand: "First Aid Beauty", description: "A daily treatment pad that contains just the right amount of Lactic and Glycolic Acids to safely and effectively exfoliate, tone, and brighten all skin types, including sensitive.", skintype: "all", category_id: 3, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/1/219_facial-radiance-pads_02.jpg")
Product.create(name: "Facial Radiance AHA Intensive Peel", brand:"First Aid Beauty", description: "Give us three minutes, and we’ll give you smooth, glowing skin. Our unique combination of acids, Lactic and Salicylic, and Mushroom Enzyme work synergistically with clay to help improve skin’s texture and clarity. This is our most potent peel – for best results read the how-to carefully. This non-abrasive, extra-strength exfoliating peel helps to resurface, smoothen, and brighten skin by removing dead skin cells.", skintype: "all", category_id: 3, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/1/219_facial-radiance-pads_02.jpg")
Product.create(name: "A-Passioni Retinol Cream", brand: "Drunk Elephant", description: "Retinol reimagined. A-Passioni Retinol Cream is a clean, cutting-edge formula that combines 1.0% vegan retinol with nourishing, superfood-rich ingredients to dramatically diminish the appearance of fine lines, deep wrinkles and sun damage revealing a vibrant, younger-looking complexion. Retinol and supportive peptides restore bounce, resilience and a brighter clarity to  skin while helping to even skin tone and texture … without the associated redness and irritation. Vitamin F, along with a curated blend of comforting passionfruit, apricot, marula and jojoba oils replenish essential lipids and moisture while antioxidant packed kale, winter cherry and xanthophylls defend against environmental stressors.
It’s like a reboot for your skin back to its most healthy, youthful state.", skintype: "all", category_id: 3, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/A-Passioni_30ml_1024x1024.jpg?v=1562690771")

# Toner
Product.create(name: "Jasmine Green Tea Balancing Toner", brand: "Herbivore", description: "Organic Jasmine Water is infused with antioxidant-rich Green Tea and a clarifying combination of Salicin-rich Willow Bark and Aloe Vera. Formulated to bring balance to combination, oily, and blemish-prone skin.", skintype: "combination", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1325-01D_HIR_HBV_JASMIN-GREENTEA_MIST_4OZ_-szd_a98dcf19-970e-4e76-a2dc-d3cb16337507.jpg?v=1562004336")
Product.create(name: "Clear Nutrient Toner", brand: "True Botanicals", description: "A balancing toner for oily and breakout-prone skin that leaves skin hydrated and refreshed.", skintype: "oily", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-nutrient-toner_x570.png?v=1557756828")
Product.create(name: "Renew Nutrient Mist", brand: "True Botanicals", description: "A hydrating mist that quenches aging and dry skin with antioxidants. And, as an added bonus, it sets makeup.", skintype: "dry", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-nutrient-mist_x570.png?v=1557756818")
Product.create(name: "Basil Yarrow Mist", brand: "NOTO", description: "A gentle cool toning mist that can awaken thirsty and tired skin, hair, and senses with the unique smell that Basil and Ylang Ylang offers.  The essential oils will soften the skin or hair, while the rose water witch hazel will tone. Use as light moisturizer or complement other products with added benefits to freshen and hydrate with soft toning on skin or hair.", skintype: "all", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-057-High-Res_1500x1500.jpg?v=1549921994")
Product.create(name: "United State", brand: "Origins", description: "Balancing Tonic is tingly-cool, retexturizing tonic refreshes, refines and rebalances faces with dry and oily places. Exfoliates away flakes, pore-clogging debris and smoothes rough spots. Laminaria helps de-shine T-zones without stripping and protect moisture levels to prevent parching. Plus aromatic Bergamot, Spearmint and Lavender to add pleasure to the process. ", skintype: "combination", category_id: 4, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0EEP01_1000x1000_0.jpg")
Product.create(name: "Zero Oil", brand: "Origins", description: "Pore purifying toner with saw palmetto & mint. This invigorating toner formulated with Saw Palmetto, Mint and Salicylic Acid instantly reduces shine and removes excess oil. Leaves skin with a smooth, matte finish. For external use only. Avoid eye area.", skintype: "oily", category_id: 4, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0GW201_1000x1000_0.jpg")
Product.create(name: "Ultra Repair Wild Oat Hydrating Toner", brand: "First Aid Beauty", description: "An alcohol-free, oatmeal-powered toner that hydrates, relieves and soothes skin while supporting overall skin health for a balanced complexion. Use after cleansing to hydrate and balance your skin. Oat milk, colloidal oatmeal and wild oats are combined with Honey and Hyaluronic Acid to help soothe, relieve redness and hydrate. Skin is left plump and prepped to absorb oils, serums or moisturizers. ", skintype: "all", category_id: 4, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/u/r/urwildoathydratingtoner_pdp_736x736.jpg")


# Serum
Product.create(name: "Bakuchiol Retinol Alternative Serum", brand: "Herbivore", description: "Derived from the Ayurvedic Babchi plant, Bakuchiol is a 100% natural, non-irritating retinol alternative. The Babchi flower flaunts a magical purple hue that occurs rarely in the botanical world. Bakuchiol harnesses this purple power to smooth fine lines and wrinkles while sealing in hydration.", skintype: "dry", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/Herbivore_Bakuchiol_Retinol_Alternative_Smoothing_Serum.jpg?v=1560800464")
Product.create(name: "Clear Repair Serum", brand: "True Botanicals", description: "A hydrating blend of concentrated nutrients that sinks into skin and helps balance your complexion.", skintype: "oily", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-repair-serum_x570.png?v=1557756811")
Product.create(name: "Renew Repair Serum", brand: "True Botanicals", description: "A hydrating blend of concentrated nutrients that sinks into skin, giving it everything it needs to look plumper, smoother, and more radiant, outperforming La Mer in independent clinical trials.", skintype: "dry", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-repair-serum_x570.png?v=1557756820")
Product.create(name: "Deep Serum", brand: "NOTO", description: "Each drop of this potent oil is a nutrient dense drink from the earth. Our Deep Serum will brighten and protect with hydration rich, age managing elements and fresh notes that will deeply penetrate skin and senses.
Great for all skin types including: sensitive, dry, acne prone, oily, or combo.", skintype: "all", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-070-High-Res_1500x1500.jpg?v=1549922465")
Product.create(name: "Original Skin", brand: "Origins", description: "Skin looking a little lackluster lately? Get your glow back with our revolutionary Willowherb-infused renewal serum. With each application, this silky-smooth serum infuses skin with glow-boosting moisture, smoothes away roughness & visibly blurs pores. The result: Skin looks vibrant and glowing.", skintype: "all", category_id: 5, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0LXJ01_1000x1000_0.jpg")
Product.create(name: "Ultra Repair Hydrating Serum", brand:"First Aid Beauty", description: "A universal serum that gives skin its daily dose of moisture for soft, smooth, youthful-looking skin. Formulated for all skin types, this hydrating gel instantly infuses skin with essential hydration to help plump and minimize the appearance of fine lines and wrinkles.", skintype: "all", category_id: 5, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/u/r/urserum_1.7oz_pdp_746x746.jpg")
Product.create(name: "Ultra Repair Liquid Recovery", brand: "First Aid Beauty", description: "A daily serum used after cleansing and toning to help hydrate and calm skin. Ultra Repair Liquid Recovery contains a blend of skin-saving ingredients, including Ahnfeltia Concinna Extract, Propolis Extract and Avena Sativa (Oat) Kernel Extract to help relieve dryness, reduce redness and calm skin. Sodium Hyaluronate helps boost skin's moisture content, leaving the complexion appearing smoother and less blotchy. This unique concentrated water base allows for easy absorption into skin.", skintype: "all", category_id: 5, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/p/d/pdp_liquidrecovery_736x736.jpg")
Product.create(name: "Anti-Redness Serum", brand: "First Aid Beauty", description: "A serum that helps calm skin, relieve visible redness and reduces flare-ups. It is recommended for anyone experiencing any type of redness including redness due to ruddy skin and chronic or temporary irritation.", skintype: "all", category_id: 5, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/0/205_anti-redness-serum_hero.jpg")
Product.create(name: "T.L.C. Framboos Glycolic Night Serum", brand: "Drunk Elephant", description: "An AHA/BHA night serum that refines and resurfaces skin to reveal a smoother and more radiant complexion. T.L.C. Framboos enhances the performance of other products by clearing the way for maximum absorption. This high-tech gel resurfaces dull skin, gently lifting dead skin cells away by dissolving the glue that holds them to the surface. Formulated with a dream team AHA/BHA blend of glycolic, lactic, tartaric, citric and salicylic acids, and blended with raspberry extract, T.L.C. Framboos sinks in easily and delivers an effective level of chemical exfoliation without the harsh side effects like dryness or sensitization. Fine lines, wrinkles and discoloration, along with excess oiliness and the appearance of pores, will appear dramatically diminished. Horse chestnut, bearberry and white tea help to calm and soothe while improving the appearance of broken capillaries. Go from a drab complexion to an absolutely luminous one, practically overnight.", skintype: "all", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/TLC-02_01_17_9c9a84be-bb2c-4800-bf08-c0a0aba40bec_1024x1024.jpg?v=1548653377")
Product.create(name: "B-Hydra Intensive Hydration Serum", brand: "Drunk Elephant", description: "B-Hydra is a cool drink of water for your thirsty skin. This ultra-hydrating serum replenishes the complexion and improves the look of skin tone and texture. Formulated with pro-vitamin B5 and pineapple ceramide, B-Hydra delivers steady hydration throughout the day, leaving the skin looking healthy and more illuminated. Blended with a unique lentil/apple/watermelon complex, B-Hydra™ helps diminish drabness, dryness and the appearance of fine lines. Your complexion will appear brighter and more youthful upon every application. This lightweight, hard-hitting serum is ideal for all skin.", skintype: "all", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/B-HydraSerum-web_1024x1024_063bceac-b048-4448-b375-1c5716d586a1_1024x1024.jpg?v=1562691587")

# Mask
Product.create(name: "Blue Clay Mask", brand: "Herbivore", description: "Formulated with Cambrian Blue Clay to detox and clarify blemish-prone skin. Ideal as a spot treatment or full face mask.", skintype: "all", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1320-07D_HBV_HIR_PINKCLAY_MASK.jpg?v=1562003123")
Product.create(name: "SQUALANE + TEA TREE DETOX MASK", brand: "Biossance", description: "Designed for oily/combination skin by helping control excess oil. French green clay helps draw out impurities within pores while tea tree helps reduce the appearance of blemishes and other imperfections. Non-drying formula features squalane to help boost the performance of tea tree as well as replenish hydration, help calm, and keep skin feeling ultra-soft. Our formula is enriched with tea tree that originates from Australia and is grown with the highest quality eco-friendly farming practices that meet ISO standards.", skintype: "combination", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/012318_Sephora_PDP_TeaTree_F_Mask_Ingredients_580x@2x.jpg?v=1549424040")
Product.create(name: "Resurfacing Moisture Mask", brand: "True Botanicals", description: "A facial in a jar. This lactic acid-based mask reveals smooth, glowing skin in five minutes, moisturizing as it exfoliates.", skintype: "all", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/resurfacing-moisture-mask_x570.png?v=1557756824")
Product.create(name: "Clear Improvement", brand: "Origins", description: "Active charcoal mask to clear pores. Nature's complexion clean-up crew clears the way for skin to act its best. Bamboo Charcoal acts like a magnet to draw out deep-dwelling pore-cloggers, White China Clay absorbs environmental toxins, Lecithin dissolves impurities. Skin looks clear, feels perfectly pure.", skintype: "oily", category_id: 6, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0T7F01_1000x1000_0.jpg")
Product.create(name: "Drink Up Intensive", brand: "Origins", description: "Put extra thirsty skin to bed. This ultra-moisturizing sleeping mask instantly floods skin with moisture & keeps skin soft, smooth & happily hydrated for 72 hours. Infused with NEW Swiss Glacier Water, Hyaluronic Acid & Avocado Butter, Drink Up™ Intensive drenches extra thirsty skin in 72 hours of non-stop hydration. Plus, it treats skin with lasting nourishment. It’s all day, every day superfood-infused hydration—while you sleep.", skintype: "dry", category_id: 6, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0T3C01_1000x1000_0.jpg")
Product.create(name: "Ultra Repair Instant Oatmeal Mask", brand: "First Aid Beauty", description: "A deeply hydrating mask that helps nourish, calm and rejuvenate distressed-looking skin. It is the perfect antidote to dry, dehydrated skin. In just 10 minutes, the mask will help restore a rough, tight complexion and achieve soft, supple results.", skintype: "all", category_id: 6, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/5/251_ultra-repari-instant-oatmeal-mask_hero.jpg")
Product.create(name: "T.L.C. Sukari Babyfacial", brand: "Drunk Elephant", description: "Babyfacial is a pro-quality AHA/BHA “facial” that resurfaces to reveal greater clarity, improved skin texture and tone, and a more youthful radiance. Think of it as an extra nudge for stubborn, dull skin (in other words, it’ll knock your cells off). This next-generation mask is an at-home “facial” that effectively yet gently exfoliates the pore lining and resurfaces by getting rid of built-up dead skin cells. With a whopping 25% AHA / 2% BHA blend of our dream team glycolic, tartaric, lactic, citric and salicylic acids, this pro-quality formula dramatically smooths texture while minimizing the look of pores, fine lines and wrinkles. Uniquely formulated with chickpea flour, pumpkin ferment and a soothing antioxidant blend of matchatea, milk thistle and apple, Babyfacial™ delivers incredible brightening and enzymatic action, improves skin’s elastic feel and reveals the look of a more even, radiant baby-soft complexion.", skintype: "all", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/babyfacial-02_01_17_1024x1024.jpg?v=1544828569")



# Eyecream
Product.create(name: "SQUALANE + MARINE ALGAE EYE CREAM", brand: "Biossance", description: "Our latest innovation in eye cream pairs the power of marine algae and paracress extract* for maximum performance. The result? A lifted look that also reduces the appearance of fine lines and wrinkles. Its melt-in texture delivers deep hydration and a perfect canvas for makeup.Melt-in. Lift Up.", skintype: "dry", category_id: 7, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/FullCap_580x@2x.jpg?v=1561680651")
Product.create(name: "Deep Repair Eye Serum", brand: "True Botanicals", description: "A super concentrated eye serum that diminishes the look of lines, dark circles, and puffiness.", skintype: "all", category_id: 7, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/deep-repair-eye-serum-award_1_x570.png?v=1557756838")
Product.create(name:"Restorative Eye Creme", brand: "Tata Harper", description: "A youth-giving, multi-correctional eye cream that targets visible signs of aging to reveal brighter looking skin around the eye area. Best for fine lines, dryness, and dark circles.", skintype: "dry", category_id: 7, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/r/e/restorative-eye-creme_goop.jpg")
Product.create(name:"A Perfect World", brand: "Origins", description: "Help prevent the damage you can’t see yet! Our lightweight, hydrating treatment with antioxidant-rich White Tea instantly renews and brightens under eyes while providing irritation-free SPF protection. It helps defend the delicate eye area and neutralize the damaging effects of UV, Infrared Rays (IR), pollution and environmental aggressors. Plus, barrier-boosting Edelweiss helps strengthen skin to prevent premature signs of aging. Oil-free. Broad spectrum 100% mineral, irritation-free SPF 20.", skintype: "all", category_id: 7, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0NKP01_1000x1000_0.jpg")
Product.create(name:"Eye Doctor", brand: "Origins", description: "When fragile skin around eyes shows crinkly, fine, dry lines, a twice-daily dose of moisture is just what the 'Doctor' ordered to help them virtually disappear. Formulated with Cucumber, Rosemary and Ginseng, helps instantly nourish and smooth the look of fine, dry lines. Shows perfect bedside manners, night or day, under makeup or alone. Ophthalmologist tested.", skintype: "all", category_id: 7, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_722B01_1000x1000_0.jpg")
Product.create(name:"Three Part Hamony", brand: "Origins", description: "Eye duo delivers nourishing day & night hydration. For day, the lightweight cream with Tazetta Lily Bulb helps soften, smooth & visibly brighten eyes. For night, the rich, luxurious cream provides comforting hydration while you sleep. The look of lines is softened. Skin's protective barrier is strengthened. Skin awakens renewed & radiant looking.", skintype: "all", category_id: 7, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0P4J01_1000x1000_5.jpg")
Product.create(name: "Detox Eye Roller", brand: "First Aid Beauty", description: "An under-eye treatment with a metal roller-ball applicator that helps minimize the appearance of under-eye puffiness and dark circles. This unique treatment helps revitalize, smooth and brighten the under-eye area.", skintype: "all", category_id: 7, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/0/202_detox-eyeroller_02.jpg")
Product.create(name: "Advanced Anti-Aging Eye Cream", brand: "Supergoop!", description: "Did you know that your eyes are one of the most sun-sensitive, yet overlooked, body parts? Enter: this ultra-hydrating, mineral-rich eye cream that reduces the visible appearance of fine lines and defends against future photoaging...all with broad spectrum protection.", skintype: "all", category_id: 7, img_path: "https://supergoop.ipscdn.net/s/files/1/1503/5658/files/EyeCream_Product.jpg?13333465311870021386")
Product.create(name: "C-Tango Multivitamin Eye Cream", brand: "Drunk Elephant", description: "A rich and restorative eye cream featuring a brightening combination of eight peptides, five forms of vitamin C, and cucumber extract for firmer, stronger-looking skin around the eye area. C-Tango is a dance of potent antioxidants, replenishing ceramides, plant oils, and soothing actives, all designed to refresh and restore a radiant appearance. Gentle enough for AM and PM use, it’s powerful enough to improve even stubborn signs of damage. ", skintype: "all", category_id: 7, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/C-Tango_pills_1024x1024.jpg?v=1522962412")


# Moisturizer
Product.create(name: "Rosewater Moisturizing Cream", brand: "Herbivore", description: "Finally, the perfect moisturizer. Pink Cloud hydrates, visibly plumps, and smooths skin leaving it with a glowing + slightly dewy finish. Includes Rosewater, Aloe Water, and White Tea Extract to moisturize, soothe and reduce the appearance of redness. Formulated for all skin types -- never greasy, oily, or sticky. Perfect under makeup or worn alone to let your skin breathe.", skintype: "all", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/Pinkcloud_4_1_-4x5.jpg?v=1562004631")
Product.create(name: "SQUALANE + PROBIOTIC GEL MOISTURIZER", brand: "Biossance", description: "A weightless, ultra-hydrating gel moisturizer infused with squalane and probiotic technology to help restore skin’s healthy-looking beauty and radiance. This No Compromise™ formula reduces the effects of daytime stressors, leaving skin visibly brighter and more balanced. Now also available in 10mL travel size. Formulated with our sugarcane-derived, sustainable squalane oil to help keep skin hydrated.", skintype: "oily",  category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/050119_Squalane-_-Probiotic-Gel-Moisturizer_PDP_1160-x-1160_580x@2x.png?v=1563812887")
Product.create(name: "Moisture Riser Cream", brand: "NOTO", description: "Raise your moisture levels with our powerful yet lightweight hyaluronic acid cream. Glow with hydration and revitalize skin’s outer layers by looking and feeling softer, more plump and nourished. A unique Herbal scent made by powerful oils of Blue Tansy, Marula, Rose Geranium, Clary Sage, and Carrot Seed may act as a calming vitamin pack of restoration to add in preventative measures for the long run.  Organic wild harvested Blue Green Algae is laced in to add a full spectrum of minerals, chlorophyll, B Vitamins, Beta-Carotene, and Pro Vitamin A.", skintype: "all", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/correct_MR_with_box_verticle_1_1500x1500.jpg?v=1549924843")
Product.create(name: "A Perfect World SPF 40", brand: "Origins", description: "This super-charged, oil-free moisturizer with antioxidant-rich White Tea surrounds skin in a protective bubble to help delay the appearance of signs of aging. Strengthens skin’s defenses against the damaging effects of pollution, Infrared Rays, ozone and other environmental aggressors. Plus, it delivers a healthy helping of hydration with SPF for UV protection. So skin stays youthfully vibrant.", skintype: "all", category_id: 8, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0NH801_1000x1000_0.jpg")
Product.create(name: "Ginzing", brand: "Origins", description: "Look like a morning person. This lightweight, oil-free, energizing moisturizer instantly hydrates & revs up radiance with Panax Ginseng & Caffeine from Coffee Beans. Instantly hydrates & revs up radiance for refreshed, healthy & vibrant skin.", skintype: "combination", category_id: 8, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0KWP01_1000x1000_0.jpg")
Product.create(name: "Make A Difference Plus+", brand: "Origins", description: "This hydrating cream instantly helps restore moisture in dry, dehydrated skin. Fortified with Rose of Jericho, Lychee & Watermelon blend, this rejuvenating cream absorbs quickly to replenish skin's natural moisture.", skintype:  "combination", category_id: 8, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0JW201_1000x1000_0.jpg")
Product.create(name: "A Perfect World", brand: "Origins", description: "We harnessed the perfect-protective powers of antioxidant-rich White Tea to help maintain youth & prevent the damage you can’t see yet. We added barrier-booster Edelweiss to this potent cream to help strengthen skin’s defenses against & neutralize skin-damaging pollution, Infrared Rays and other environmental aggressors. Plus, it hydrates to maximize skin's moisture barrier.", skintype: "all" , category_id: 8, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0NL301_1000x1000_0.jpg")
Product.create(name: "Ginzing", brand: "Origins", description: "Ultra-Hydrating Energy-Boosting Cream. Major hydration, major energy. Our ultra-hydrating energizer with Coffee Seed Oil & Cupuacu Butter gets skin glowing. Hydrates for 24 hours, restores radiance, rapidly refreshes & leaves skin energized.", skintype: "dry", category_id: 8, img_path: "https://www.origins.com/media/export/cms/products/1000x1000/origins_sku_0P1501_1000x1000_0.jpg")
Product.create(name: "5 in 1 Face Cream SPF 30", brand: "First Aid Beauty", description: "A multitasking, age-delay moisturizer with SPF 30 protection. This face cream supplies your skin with ingredients to help protect your complexion and keep it looking younger and more vibrant.", skintype: "all", category_id: 8, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/0/209_5-in-1-face-cream-spf-30_hero.jpg")
Product.create(name: "Ultra Repair Pure Mineral Sunscreen Moisturizer SPF 40", brand: "First Aid Beauty", description: "Formulated with soothing hydrators and high-level, broad spectrum UVA/UVB protection that is safe for sensitive skin. This hydrating and nourishing formulation has a rich, velvety texture and helps keep skin protected, hydrated and soothed wherever your day takes you.", skintype: "all", category_id: 8, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/4/3/433_ultra-repair-pure-mineral-sunscreen_hero.jpg")
Product.create(name: "Hello FAB Coconut Water Cream", brand: "First Aid Beauty", description: "Oil-free refreshingly light water cream moisturizer infused with skin nourishing Coconut Water hydrocharges your skin with a burst of electrolyte-rich moisture for softer, smoother, healthier-looking skin.", skintype: "combination", category_id: 8, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/c/o/cocowatercream_w-swatch_736x736.jpg")
Product.create(name: "Skin Rescue Daily Face Cream", brand: "First Aid Beauty", description: "A lightweight, non-comedogenic lotion that helps hydrate, calm and protect skin. This daily cream softens and soothes skin without clogging pores for a healthier, plumper-looking complexion.", skintype: "combination", category_id: 8, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/2/0/208_daily-face-cream_hero.jpg")
Product.create(name: "Lala Retro Whipped Cream", brand: "Drunk Elephant", description: "Introducing a multi-faceted rescue cream that provides replenishing barrier support by reinforcing skin's acid mantle and defending against the effects of everyday stressors. This multi-faceted rescue cream, infused with six rare African oils and plant ceramide complex, provides replenishing barrier support by reinforcing skin's acid mantle and defending against the effects of everyday stressors. Sodium hyaluronate crosspolymer easily soaks in to release intense hydration. In addition, antioxidant-rich fermented green tea helps combat signs of aging. Loaded with omega acids, Lala helps skin retain long-lasting moisture, forming a protective layer that allows skin to function at its optimal level. Lala Retro is a whipped, dream-come-true for tired, dry skin. ", skintype: "dry", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/Lala_0001_Lala_no_lid_goop_1_1024x1024.jpg?v=1562873287")
Product.create(name: "Protini Polypeptide Cream", brand: "Drunk Elephant", description: "This breakthrough protein moisturizer combines an unprecedented array and concentration of signal peptides, growth factors, supportive amino acids and pygmy waterlily for visible and immediate improvement in the appearance of skin’s tone, texture and firmness. Protini’s proprietary formula delivers younger, revived-looking skin, almost from the first application. Lines, wrinkles and signs of sun-damage appear reduced and skin feels strengthened and moisturized.", skintype: "all", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/NEW_Protini_2019_0000_05-31-19_Protini_cap-behind_goop_1024x1024.jpg?v=1564068008")



# Sunscreen
Product.create(name: "SQUALANE + MINERAL SPF 45", brand: "Biossance", description: "A clean, lightweight and non-greasy daily mineral facial sunscreen that protects skin from UVA/ UVB and infrared rays, while defending against environmental stressors. Plus, this No Compromise™ formula makes the perfect primer for easy makeup application.", skintype: "all", category_id: 9, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/021119_Sephora_PDP_2000x2000_300dpi_F_SPF_3_580x@2x.jpg?v=1558661685")
Product.create(name: "Everyday Sheer Coverage SPF 20", brand: "True Botanicals", description: "A tinted SPF20 sunscreen that uses the safest source of broad spectrum protection: non-nano zinc oxide. Available in three sheer tints.", skintype: "all", category_id: 9, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/everyday-sheer-coverage-light_x570.png?v=1557859682")
Product.create(name: "Invisible Shield", brand: "Glossier", description: "Not optional. If you don’t already use sun protection every day, now’s the time to start. If you do, good! Now it’s time for an upgrade. Introducing sunscreen for people who hate wearing sunscreen—a clear watergel formula filled with active microcapsules that instantly absorbs into skin with no greasy residue and zero white cast. It helps prevent sun damage and skin cancer, but also works to neutralize harmful free radicals, and keeps pollutant junk from getting in there in the first place—that’s the “+”. We want you to use it every single morning as the last step in your skincare routine.", skintype: "all", category_id: 9, img_path: "https://static-assets.glossier.com/production/spree/images/attachments/000/003/754/portrait_normal/InvisibleShield.jpg?1556563183")
Product.create(name: "Everyday Sunscreen SPF 50", brand: "Supergoop!", description: "The Supergoop! original. This water-resistant formula is perfect for everyday use on face and body. It's fast-absorbing and lightweight, but with ultra-moisturizing results. And, it's made with natural extracts of citrus, basil, and bois de rose, so you'll leave that typical sunscreen smell behind.", skintype: "all", category_id: 9, img_path: "https://supergoop.ipscdn.net/s/files/1/1503/5658/files/EVD2.4oz_Product.jpg?6987995200279658693")
Product.create(name: "Unseen Sunscreen SPF 40", brand: "Supergoop!", description: "Our 100% invisible, 100% game-changing makeup-gripping primer with SPF 40. This award-winning formula is also weightless and scentless, and it has a slightly glowy effect that allows you to create any type of (makeup or no-makeup) look. But that's not all... It also contains clean, skin-soothing ingredients like red algae, which helps protect your skin from the blue light that's emitted by your phone and computer. ", skintype: "all", category_id: 9, img_path: "https://supergoop.ipscdn.net/s/files/1/1503/5658/t/3/assets/f1538053709882_Unseen_BestofBeautyALLURE_1.jpg?11470596538086220426")
Product.create(name: "Smooth and Poreless 100% Mineral Matte Screen", brand: "Supergoop!", description: "Introducing perfect, poreless skin in a tube... This best-seller is a 100% mineral primer in one translucent formula that blurs pores and mattifies skin. Wear underneath makeup for more coverage during the week, or on its own for less coverage during the weekend - and either way, you can rest assured that you're getting SPF 40 protection. Major bonus points for the fact that butterfly bush extract helps guard your skin from blue light too (more on that below).", skintype: "oily", category_id: 9, img_path: "https://supergoop.ipscdn.net/s/files/1/1503/5658/files/MatteScreen_Product.jpg?2029733220851150032")
Product.create(name: "Defense Refresh Setting Mist", brand: "Supergoop!", description: "A refreshing sunscreen setting spray that lets you reapply SPF over your makeup. Infused with antioxidant-rich rosemary, this weightless spray locks in your morning makeup, helps absorb oils throughout the day and leaves a natural finish. Reapply it throughout the day for added protection and an invigorating pick-me-up.", skintype: "all", category_id: 9, img_path: "https://supergoop.ipscdn.net/s/files/1/1503/5658/files/DRMist3.4_Product.jpg?1591696128906667850")
Product.create(name: "Umbra Sheer Physical Daily Defense SPF 30", brand: "Drunk Elephant", description: "A sheer, physical sunscreen that delivers powerful  broad spectrum UVA/UVB protection and helps aid in the prevention of free radical and oxidative damage. Umbra Sheer is a daily sunscreen loaded with potent antioxidants like astaxanthin, grape juice and sunflower shoot extracts to minimize the appearance of photoaging for a more youthful-looking complexion. Infused with raspberry seed and marula oils, Umbra Sheer delivers essential moisture and minimizes the look of fine lines and wrinkles for skin that appears healthy and preserved. This unique formulation is ideal for daily use without any white reside or greasiness. Umbra Sheer™ is suitable for all skin, including the most sensitive.", skintype: "all", category_id: 9, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/Umbra-90-web_06c6b6a6-8097-4114-81ee-ede2ef3e8a4d_1024x1024.jpg?v=1544650492")




# Oil
Product.create(name: "Rooted Oil", brand: "NOTO", description: "Rooted Oil was the first piece that launched the NOTO collection.
A moisture rich uni-sexy scent for skin and hair and modern take on the shamanistic smell of burning palo santo and other oils of nature. Deep yet subtle undertones of smoke, wood, and earth and hints of bergamot and cardamom give this scent layers of grounding.  With a base of argan oil, it dually acts as a nourishing hair oil. Beards welcome.", skintype: "all", category_id: 10, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-065-High-Res_1500x1500.jpg?v=1549928019")
Product.create(name: "Agender Oil", brand: "NOTO", description: "WHEREVER you choose to grow hair, this oil is here to soften and protect. Great for the body too! The perfect harmony between strong and soft. Moisture rich Organic Hemp Seed Oil is mixed with the smokey strong Vetiver and sweet Lavender to create the perfect harmony and nutrient dense treatment.", skintype: "all", category_id: 10, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-062-High-Res_1500x1500.jpg?v=1549921096")
Product.create(name: "Beautifying Face Oil", brand: "Tata Harper", description: "A glow giving face oil to improve radiance and revitalize the look of the skin. Best for dry, dull, or uneven skin in need of essential nutrients. This lightweight face oil is your radiance restoring booster. Our glow complex revives dull, fatigued skin with vitamin B from camellia oil while antioxidants help fight the effects of free radicals that can diminish your glow and make you look older than you are. This formula restores radiance with 5 sources of glow, 7 sources of antioxidants, and 3 sources to smooth and soften skin texture.", skintype: "dry", category_id: 10, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/b/e/beautifying-face-oil_goop_1.jpg")
Product.create(name: "Ultra Repair Cannabis & Oat Dry Oil", brand: "First Aid Beauty", description: "A soothing treatment oil infused with Cannabis Sativa Seed Oil from hemp and Colloidal Oatmeal to help de-stress, relieve, and nourish dry, reactive, and sensitive skin. This antioxidant-rich facial oil is formulated with a blend of 16 cold-pressed active botanicals including Cannabis Sativa Seed Oil, rich in omegas and fatty acids, and Colloidal Oatmeal. Together they work to help calm and soothe dry, distressed skin. Arnica Montana Flower Extract and Borage Seed Oil help hydrate and accelerate skin’s natural healing processes. This unique dry oil quickly and fully penetrates so it will never leave a greasy after-feel. ", skintype: "all", category_id: 10, img_path: "https://www.firstaidbeauty.com/pub/media/catalog/product/cache/image/593ca0152a366e0f697bf8f144497f65/c/o/codo_pdp_746x746_1.jpg")
Product.create(name: "Virgin Marula Luxury Facial Oil", brand: "Drunk Elephant", description: "Straight from the 'pip' of the marula fruit, our Virgin Marula Luxury Facial Oil is untouched by any chemical or fragrance, natural or synthetic and remains in its purest form. Drunk Elephant uses a proprietary raw, cold-press extraction and filtration process, resulting in the purest and most concentrated form of the oil, highly absorbable, with its delicate polyphenol antioxidant and fatty acid compounds preserved. Our Marula Oil contains greater concentrations of polyphenols than dark chocolate, green or black teas, which means powerful antioxidant defense against pollution + damaging environmental free radicals.", skintype: "all", category_id: 10, img_path: "https://cdn.shopify.com/s/files/1/0209/8446/products/Marula-15_1024x1024.jpg?v=1534291498")
