# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: "Emi")
User.create(name: "Catherine")

Category.create(name: "oil cleanser")
Category.create(name: "water based cleanser")
Category.create(name: "exfoliator")
Category.create(name: "toner")
Category.create(name: "serum")
Category.create(name: "mask")
Category.create(name: "eyecream")
Category.create(name: "moisturizer")
Category.create(name: "sunscreen")
Category.create(name: "facial oil")

# Oil Cleanser

Product.create(name: "SQUALANE + ANTIOXIDANT CLEANSING OIL", brand: "Biossance", description: "The lightweight oil lifts away makeup and impurities, then rinses completely clean with water. Formulated with our sugarcane-derived, sustainable squalane oil, it helps keep skin hydrated and feeling fresh.", skintype: "all", category_id: 1, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/Cleansing-Oil_Full_white-1160-x-1160_580x@2x.png?v=1560972953")
Product.create(name: "Pre Cleanse Oil", brand: "True Botanicals", description: "This silky oil thoroughly loosens dirt, sunscreen, and stubborn makeup. Remove with cleanser or warm wash cloth to purify pores. Leaves skin clean, hydrated, and dewy.", skintype: "all", category_id: 1, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/pre-cleanse-oil_012de282-978a-4ec9-a9b0-67610ba1d613_x570.png?v=1557756849")
Product.create(name: "Nourishing Oil Cleanser", brand: "Tata Harper", description: "A multi-vitamin cleansing oil that breaks down buildup and dissolves makeup without stripping the skin for a soft, supple feeling. Best for makeup removal and dry, uneven skin.", skintype: "dry", category_id: 1, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/n/o/nourishing-oil-cleanser_goop.jpg")

# Water based cleanser
Product.create(name: "Bamboo Charcoal Cleanser", brand: "Herbivore", description: "Bamboo Charcoal has been used for centuries in the Far East. Bamboo charcoal does wonders to purify the skin by cleansing it of dirt, drawing impurities from deep within your pores. Gentle yet effective, Bamboo Charcoal works especially well to clean and care for oily, combination and blemish-prone skin types.", skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1320-25C_HBV_HIR_BAMBOOCHARCOAL_SOAP.jpg?v=1562001461")
Product.create(name: "Renew Nourishing Cleanser", brand: "True Botanicals", description: "A gentle cleanser for aging and dry skin that nourishes as it cleanses.", skintype: "dry", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-nourishing-cleanser-award_x570.png?v=1560277394")
Product.create(name: "Clear Nourishing Cleanser", brand: "True Botanicals", description: "A purifying cleanser for oily and breakout-prone skin that nourishes as it cleanses and gently exfoliates." ,skintype: "oily", category_id: 2, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-nourishing-cleanser_x570.png?v=1557756826")

# Exfoliator
Product.create(name: "Resurface Scrub", brand: "NOTO", description: "Welcome to your new favorite scrub of all time...Skin so smooth - you’ll be amazed .  Polish and cleanse  with Blood orange, alpha hydroxy acids and walnut powder, combining to create a gentle exfoliate that leaves your skin feeling brand new.  We recommend using this scrub twice a week - and please do protect your skin after use as AHA’s can leave skin sensitive towards the sun.", skintype: "all", category_id: 3, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-054-High-Res_1500x1500.jpg?v=1549926757")
Product.create(name: "Vitamin C Probiotic Face Polish", brand: "OSEA", description: "This potent powdered exfoliant instantly brightens as it polishes to reveal luminous, vibrant skin. Our unique formulation is the first to combine pure Vitamin C with vegan Probiotics. Reduces the look of hyperpigmentation, smoothes & visibly brightens your complexion. Fermented Pomegranate enzymes gently remove surface build-up. Finely ground organic Bamboo and Rice powders infused with mineral-rich Seaweeds work to delicately buff away dull skin. Our ultra-potent, preservative-free formula is kept fresh until activated with water, transforming it into a creamy paste for a youthful, luminous glow.", skintype: "all", category_id: 3, img_path: "https://cdn.shopify.com/s/files/1/1368/9993/products/OSEA-vitamin-c-probiotic-polish-r_db1b24a7-9ab9-4f70-bf2f-9c2372d01735.jpg?v=1544734230")
Product.create(name: "Solution", brand: "Glossier", description: "Unlike physical exfoliators that scrub the surface of your skin, Solution gently sloughs away dead skin through chemical exfoliation, revealing a fresh complexion. Daily use helps clear up acne and blackheads and reduces visible redness and enlarged pores. Overall, skin’s texture appears smoother, softer, and glowier. Solution contains a particular 10% blend of three acid groups: Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), and Polyhydroxy Acid (PHA). Acids are your friend.", skintype: "all", category_id: 3, img_path: "https://static-assets.glossier.com/production/spree/images/attachments/000/003/765/portrait_normal/Solution.jpg?1556564148")

# Toner
Product.create(name: "Jasmine Green Tea Balancing Toner", brand: "Herbivore", description: "Organic Jasmine Water is infused with antioxidant-rich Green Tea and a clarifying combination of Salicin-rich Willow Bark and Aloe Vera. Formulated to bring balance to combination, oily, and blemish-prone skin.", skintype: "combination", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1325-01D_HIR_HBV_JASMIN-GREENTEA_MIST_4OZ_-szd_a98dcf19-970e-4e76-a2dc-d3cb16337507.jpg?v=1562004336")
Product.create(name: "Clear Nutrient Toner", brand: "True Botanicals", description: "A balancing toner for oily and breakout-prone skin that leaves skin hydrated and refreshed.", skintype: "oily", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-nutrient-toner_x570.png?v=1557756828")
Product.create(name: "Renew Nutrient Mist", brand: "True Botanicals", description: "A hydrating mist that quenches aging and dry skin with antioxidants. And, as an added bonus, it sets makeup.", skintype: "dry", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-nutrient-mist_x570.png?v=1557756818")
Product.create(name: "Basil Yarrow Mist", brand: "NOTO", description: "A gentle cool toning mist that can awaken thirsty and tired skin, hair, and senses with the unique smell that Basil and Ylang Ylang offers.  The essential oils will soften the skin or hair, while the rose water witch hazel will tone. Use as light moisturizer or complement other products with added benefits to freshen and hydrate with soft toning on skin or hair.", skintype: "all", category_id: 4, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-057-High-Res_1500x1500.jpg?v=1549921994")

# Serum
Product.create(name: "Bakuchiol Retinol Alternative Serum", brand: "Herbivore", description: "Derived from the Ayurvedic Babchi plant, Bakuchiol is a 100% natural, non-irritating retinol alternative. The Babchi flower flaunts a magical purple hue that occurs rarely in the botanical world. Bakuchiol harnesses this purple power to smooth fine lines and wrinkles while sealing in hydration.", skintype: "dry", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/Herbivore_Bakuchiol_Retinol_Alternative_Smoothing_Serum.jpg?v=1560800464")
Product.create(name: "Clear Repair Serum", brand: "True Botanicals", description: "A hydrating blend of concentrated nutrients that sinks into skin and helps balance your complexion.", skintype: "oily", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/clear-repair-serum_x570.png?v=1557756811")
Product.create(name: "Renew Repair Serum", brand: "True Botanicals", description: "A hydrating blend of concentrated nutrients that sinks into skin, giving it everything it needs to look plumper, smoother, and more radiant, outperforming La Mer in independent clinical trials.", skintype: "dry", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/renew-repair-serum_x570.png?v=1557756820")
Product.create(name: "Deep Serum", brand: "NOTO", description: "Each drop of this potent oil is a nutrient dense drink from the earth. Our Deep Serum will brighten and protect with hydration rich, age managing elements and fresh notes that will deeply penetrate skin and senses.
Great for all skin types including: sensitive, dry, acne prone, oily, or combo.", skintype: "all", category_id: 5, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-070-High-Res_1500x1500.jpg?v=1549922465")

# Mask
Product.create(name: "Blue Clay Mask", brand: "Herbivore", description: "Formulated with Cambrian Blue Clay to detox and clarify blemish-prone skin. Ideal as a spot treatment or full face mask.", skintype: "all", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/1320-07D_HBV_HIR_PINKCLAY_MASK.jpg?v=1562003123")
Product.create(name: "SQUALANE + TEA TREE DETOX MASK", brand: "Biossance", description: "Designed for oily/combination skin by helping control excess oil. French green clay helps draw out impurities within pores while tea tree helps reduce the appearance of blemishes and other imperfections. Non-drying formula features squalane to help boost the performance of tea tree as well as replenish hydration, help calm, and keep skin feeling ultra-soft. Our formula is enriched with tea tree that originates from Australia and is grown with the highest quality eco-friendly farming practices that meet ISO standards.", skintype: "combination", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/012318_Sephora_PDP_TeaTree_F_Mask_Ingredients_580x@2x.jpg?v=1549424040")
Product.create(name: "Resurfacing Moisture Mask", brand: "True Botanicals", description: "A facial in a jar. This lactic acid-based mask reveals smooth, glowing skin in five minutes, moisturizing as it exfoliates.", skintype: "all", category_id: 6, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/resurfacing-moisture-mask_x570.png?v=1557756824")

# Eyecream
Product.create(name: "SQUALANE + MARINE ALGAE EYE CREAM", brand: "Biossance", description: "Our latest innovation in eye cream pairs the power of marine algae and paracress extract* for maximum performance. The result? A lifted look that also reduces the appearance of fine lines and wrinkles. Its melt-in texture delivers deep hydration and a perfect canvas for makeup.Melt-in. Lift Up.", skintype: "dry", category_id: 7, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/FullCap_580x@2x.jpg?v=1561680651")
Product.create(name: "Deep Repair Eye Serum", brand: "True Botanicals", description: "A super concentrated eye serum that diminishes the look of lines, dark circles, and puffiness.", skintype: "all", category_id: 7, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/deep-repair-eye-serum-award_1_x570.png?v=1557756838")
Product.create(name:"Restorative Eye Creme", brand: "Tata Harper", description: "A youth-giving, multi-correctional eye cream that targets visible signs of aging to reveal brighter looking skin around the eye area. Best for fine lines, dryness, and dark circles.", skintype: "dry", category_id: 7, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/r/e/restorative-eye-creme_goop.jpg")

# Moisturizer
Product.create(name: "Rosewater Moisturizing Cream", brand: "Herbivore", description: "Finally, the perfect moisturizer. Pink Cloud hydrates, visibly plumps, and smooths skin leaving it with a glowing + slightly dewy finish. Includes Rosewater, Aloe Water, and White Tea Extract to moisturize, soothe and reduce the appearance of redness. Formulated for all skin types -- never greasy, oily, or sticky. Perfect under makeup or worn alone to let your skin breathe.", skintype: "all", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0203/8454/products/Pinkcloud_4_1_-4x5.jpg?v=1562004631")
Product.create(name: "SQUALANE + PROBIOTIC GEL MOISTURIZER", brand: "Biossance", description: "A weightless, ultra-hydrating gel moisturizer infused with squalane and probiotic technology to help restore skin’s healthy-looking beauty and radiance. This No Compromise™ formula reduces the effects of daytime stressors, leaving skin visibly brighter and more balanced. Now also available in 10mL travel size. Formulated with our sugarcane-derived, sustainable squalane oil to help keep skin hydrated.", skintype: "oily",  category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/050119_Squalane-_-Probiotic-Gel-Moisturizer_PDP_1160-x-1160_580x@2x.png?v=1563812887")
Product.create(name: "Moisture Riser Cream", brand: "NOTO", description: "Raise your moisture levels with our powerful yet lightweight hyaluronic acid cream. Glow with hydration and revitalize skin’s outer layers by looking and feeling softer, more plump and nourished. A unique Herbal scent made by powerful oils of Blue Tansy, Marula, Rose Geranium, Clary Sage, and Carrot Seed may act as a calming vitamin pack of restoration to add in preventative measures for the long run.  Organic wild harvested Blue Green Algae is laced in to add a full spectrum of minerals, chlorophyll, B Vitamins, Beta-Carotene, and Pro Vitamin A.", skintype: "all", category_id: 8, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/correct_MR_with_box_verticle_1_1500x1500.jpg?v=1549924843")


# Sunscreen
Product.create(name: "SQUALANE + MINERAL SPF 45", brand: "Biossance", description: "A clean, lightweight and non-greasy daily mineral facial sunscreen that protects skin from UVA/ UVB and infrared rays, while defending against environmental stressors. Plus, this No Compromise™ formula makes the perfect primer for easy makeup application.", skintype: "all", category_id: 9, img_path: "https://cdn.shopify.com/s/files/1/0806/5829/products/021119_Sephora_PDP_2000x2000_300dpi_F_SPF_3_580x@2x.jpg?v=1558661685")
Product.create(name: "Everyday Sheer Coverage SPF 20", brand: "True Botanicals", description: "A tinted SPF20 sunscreen that uses the safest source of broad spectrum protection: non-nano zinc oxide. Available in three sheer tints.", skintype: "all", category_id: 9, img_path: "https://cdn.shopify.com/s/files/1/0545/1009/products/everyday-sheer-coverage-light_x570.png?v=1557859682")
Product.create(name: "Invisible Shield", brand: "Glossier", description: "Not optional. If you don’t already use sun protection every day, now’s the time to start. If you do, good! Now it’s time for an upgrade. Introducing sunscreen for people who hate wearing sunscreen—a clear watergel formula filled with active microcapsules that instantly absorbs into skin with no greasy residue and zero white cast. It helps prevent sun damage and skin cancer, but also works to neutralize harmful free radicals, and keeps pollutant junk from getting in there in the first place—that’s the “+”. We want you to use it every single morning as the last step in your skincare routine.", skintype: "all", category_id: 9, img_path: "https://static-assets.glossier.com/production/spree/images/attachments/000/003/754/portrait_normal/InvisibleShield.jpg?1556563183")

# Oil
Product.create(name: "Rooted Oil", brand: "NOTO", description: "Rooted Oil was the first piece that launched the NOTO collection.
A moisture rich uni-sexy scent for skin and hair and modern take on the shamanistic smell of burning palo santo and other oils of nature. Deep yet subtle undertones of smoke, wood, and earth and hints of bergamot and cardamom give this scent layers of grounding.  With a base of argan oil, it dually acts as a nourishing hair oil. Beards welcome.", skintype: "all", category_id: 10, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-065-High-Res_1500x1500.jpg?v=1549928019")
Product.create(name: "Agender Oil", brand: "NOTO", description: "WHEREVER you choose to grow hair, this oil is here to soften and protect. Great for the body too! The perfect harmony between strong and soft. Moisture rich Organic Hemp Seed Oil is mixed with the smokey strong Vetiver and sweet Lavender to create the perfect harmony and nutrient dense treatment.", skintype: "all", category_id: 10, img_path: "https://cdn.shopify.com/s/files/1/1627/2127/products/Noto-062-High-Res_1500x1500.jpg?v=1549921096")
Product.create(name: "BEAUTIFYING FACE OIL", brand: "Tata Harper", description: "A glow giving face oil to improve radiance and revitalize the look of the skin. Best for dry, dull, or uneven skin in need of essential nutrients. This lightweight face oil is your radiance restoring booster. Our glow complex revives dull, fatigued skin with vitamin B from camellia oil while antioxidants help fight the effects of free radicals that can diminish your glow and make you look older than you are. This formula restores radiance with 5 sources of glow, 7 sources of antioxidants, and 3 sources to smooth and soften skin texture.", skintype: "dry", category_id: 10, img_path: "https://www.tataharperskincare.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/b/e/beautifying-face-oil_goop_1.jpg")
